#!/bin/bash

export PROXY_PROFILE=${PROXY_PROFILE-debug}
export ENGINE_LABEL_VALUE=${ENGINE_LABEL_VALUE-tiflash}
export PROMETHEUS_METRIC_NAME_PREFIX=${PROMETHEUS_METRIC_NAME_PREFIX-"${ENGINE_LABEL_VALUE}_proxy_"}
