{
 "title": "Test-Cluster-TiKV-FastTune (Alpha)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "key_command",
    "label": "key_command",
    "query": "label_values(tikv_storage_command_total, type)"
   },
   {
    "name": "command",
    "label": "command",
    "query": "label_values(tikv_storage_command_total, type)"
   },
   {
    "name": "db",
    "label": "db",
    "query": "label_values(tikv_engine_block_cache_size_bytes, db)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(tikv_engine_size_bytes, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Fast Tune", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Imbalance write ?",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}-write"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc (total)"
    }
   ]
  },
  {
   "title": "Imbalance read ?",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_get|kv_batch_get|kv_batch_get_command|coprocessor\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}-read"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_get|kv_batch_get|kv_batch_get_command|coprocessor\"}[1m]))",
     "legendFormat": "read-rpc (total)"
    }
   ]
  },
  {
   "title": "Write-RPC too slow ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m])) by (le))",
     "legendFormat": "write-rpc-duration-999%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m])) by (le))",
     "legendFormat": "write-rpc-duration-99%"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m])) by (le))",
     "legendFormat": "write-rpc-duration-max"
    }
   ]
  },
  {
   "title": "Read-RPC too slow ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"kv_get|kv_batch_get|kv_batch_get_command|coprocessor\"}[1m])) by (le))",
     "legendFormat": "read-rpc-duration-999%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"kv_get|kv_batch_get|kv_batch_get_command|coprocessor\"}[1m])) by (le))",
     "legendFormat": "read-rpc-duration-99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"kv_get|kv_batch_get|kv_batch_get_command|coprocessor\"}[1m])) by (le))",
     "legendFormat": "read-rpc-duration-max"
    }
   ]
  },
  {
   "title": "Latch wait too long ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_scheduler_latch_wait_duration_seconds_bucket{instance=~\"$instance\", type=~\"prewrite|commit|acquire_pessimistic_lock\"}[1m])) by (le))",
     "legendFormat": "duration-999%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_scheduler_latch_wait_duration_seconds_bucket{instance=~\"$instance\", type=~\"prewrite|commit|acquire_pessimistic_lock\"}[1m])) by (le))",
     "legendFormat": "duration-max"
    }
   ]
  },
  {
   "title": "Coprocessor-RPC too slow ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"coprocessor\"}[1m])) by (le))",
     "legendFormat": "copr-duration-999%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"coprocessor\"}[1m])) by (le))",
     "legendFormat": "copr-duration-99%"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"coprocessor\"}[1m])) by (le))",
     "legendFormat": "copr-duration-max"
    }
   ]
  },
  {
   "title": "Wait for available raftstore threads ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_request_wait_time_duration_secs_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "wait-duration-999%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_request_wait_time_duration_secs_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "wait-duration-99%"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_raftstore_request_wait_time_duration_secs_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "wait-max"
    }
   ]
  },
  {
   "title": "Coprocessor handle too slow ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_handle_seconds_bucket{instance=~\"$instance\", req=~\"index\"}[1m])) by (le))",
     "legendFormat": "index-dur-99%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_handle_seconds_bucket{instance=~\"$instance\", req=~\"select\"}[1m])) by (le))",
     "legendFormat": "select-dur-99%"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_coprocessor_request_handle_seconds_bucket{instance=~\"$instance\", req=~\"select\"}[1m])) by (le))",
     "legendFormat": "select-dur-max"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_coprocessor_request_handle_seconds_bucket{instance=~\"$instance\", req=~\"index\"}[1m])) by (le))",
     "legendFormat": "index-dur-max"
    }
   ]
  },
  {
   "title": "RaftDB sync WAL too slow ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "avg(tikv_engine_wal_file_sync_micro_seconds{instance=~\"$instance\", db=\"raft\",type=\"wal_file_sync_percentile99\"})",
     "legendFormat": "raftdb-wal-duration-99%"
    },
    {
     "expr": "avg(tikv_engine_wal_file_sync_micro_seconds{instance=~\"$instance\", db=\"raft\",type=\"wal_file_sync_max\"})",
     "legendFormat": "raftdb-wal-duration-max"
    }
   ]
  },
  {
   "title": "Wait for available coprocessor threads ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_coprocessor_request_wait_seconds_bucket{instance=~\"$instance\", req=~\"select|index\"}[1m])) by (le))",
     "legendFormat": "duration-99%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_coprocessor_request_wait_seconds_bucket{instance=~\"$instance\", req=~\"select|index\"}[1m])) by (le))",
     "legendFormat": "duration-999%"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_coprocessor_request_wait_seconds_bucket{instance=~\"$instance\", req=~\"select|index\"}[1m])) by (le))",
     "legendFormat": "duration-max"
    }
   ]
  },
  {
   "title": "RaftDB write too slow ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(tikv_engine_write_micro_seconds{instance=~\"$instance\", db=\"raft\",type=\"write_percentile99\"})",
     "legendFormat": "duration-99%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "avg(tikv_engine_write_micro_seconds{instance=~\"$instance\", db=\"raft\",type=\"write_max\"})",
     "legendFormat": "duration-max"
    }
   ]
  },
  {
   "title": "Wait for available coprocessor threads ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_futurepool_pending_task_total{instance=~\"$instance\", name=~\"cop-normal\"}[1m]))",
     "legendFormat": "wait-queue"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    }
   ]
  },
  {
   "title": "KVDB write too slow ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(tikv_engine_write_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"write_percentile99\"})",
     "legendFormat": "duration-99%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "avg(tikv_engine_write_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"write_max\"})",
     "legendFormat": "duration-max"
    }
   ]
  },
  {
   "title": "Too much coprocessor requests ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "sum(rate(tikv_coprocessor_request_duration_seconds_count{instance=~\"$instance\", req=\"index\"}[1m]))",
     "legendFormat": "index-req"
    },
    {
     "expr": "sum(rate(tikv_coprocessor_request_duration_seconds_count{instance=~\"$instance\", req=\"select\"}[1m]))",
     "legendFormat": "select-req"
    }
   ]
  },
  {
   "title": "Wait for available scheduler threads ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_scheduler_wait_for_process_duration_seconds_bucket{instance=~\"$instance\", type=~\"prewrite|commit|acquire_pessimistic_lock\"}[1m])) by (le))",
     "legendFormat": "wait-duration-999%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_scheduler_wait_for_process_duration_seconds_bucket{instance=~\"$instance\", type=~\"prewrite|commit|acquire_pessimistic_lock\"}[1m])) by (le))",
     "legendFormat": "wait-duration-99%"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_scheduler_wait_for_process_duration_seconds_bucket{instance=~\"$instance\", type=~\"prewrite|commit|acquire_pessimistic_lock\"}[1m])) by (le))",
     "legendFormat": "wait-duration-max"
    }
   ]
  },
  {
   "title": "KVDB block cache miss ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "sum(rate(tikv_engine_cache_efficiency{instance=~\"$instance\", db=\"kv\", type=\"block_cache_data_miss\"}[1m])) / (sum(rate(tikv_engine_cache_efficiency{db=\"kv\", type=\"block_cache_data_hit\"}[1m])) + sum(rate(tikv_engine_cache_efficiency{db=\"kv\", type=\"block_cache_data_miss\"}[1m])))",
     "legendFormat": "data-miss-rate"
    }
   ]
  },
  {
   "title": "Wait for available scheduler threads ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_futurepool_pending_task_total{instance=~\"$instance\", name=~\"sched-worker-pool\"}[1m]))",
     "legendFormat": "wait-queue"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    }
   ]
  },
  {
   "title": "Coprocessor scan too much ? (include MVCC)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(tikv_coprocessor_scan_details{instance=~\"$instance\", req=~\"select|index\", cf=\"default\"}[1m])) + sum(rate(tikv_coprocessor_scan_details{instance=~\"$instance\", req=~\"select|index\", cf=\"write\"}[1m])))",
     "legendFormat": "copr-scan-number"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    }
   ]
  },
  {
   "title": "Has write stall ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(tikv_engine_write_stall{instance=~\"$instance\", type=\"write_stall_max\"})",
     "legendFormat": "duration-max"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "max(tikv_engine_write_stall{instance=~\"$instance\", type=\"write_stall_percentile99\"})",
     "legendFormat": "duration-99"
    }
   ]
  },
  {
   "title": "KVDB scan too much deleted data  ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_coprocessor_rocksdb_perf{instance=~\"$instance\" ,metric=\"internal_delete_skipped_count\"}[1m]))",
     "legendFormat": "kvdb-delete-skipped-count"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    }
   ]
  },
  {
   "title": "Wait for available apply threads ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_wait_time_duration_secs_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "wait-duration-999%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_wait_time_duration_secs_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "wait-duration-99%"
    }
   ]
  },
  {
   "title": "KVDB frontend flow ? (read-flow may hit page-cache)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"wal_file_bytes\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"bytes_written\"}[1m]))",
     "legendFormat": "write-flow"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"bytes_read\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"iter_bytes_read\"}[1m]))",
     "legendFormat": "read-flow"
    }
   ]
  },
  {
   "title": "KVDB write too slow ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(tikv_engine_write_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"write_percentile99\"})",
     "legendFormat": "duration-99%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "avg(tikv_engine_write_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"write_max\"})",
     "legendFormat": "duration-max"
    }
   ]
  },
  {
   "title": "KVDB read too slow ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(tikv_engine_get_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"get_percentile99\"})",
     "legendFormat": "duration-99%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "avg(tikv_engine_get_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"get_max\"})",
     "legendFormat": "duration-max"
    }
   ]
  },
  {
   "title": "KVDB compaction flow has jitter? (read-flow may hit page-cache)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"flush_write_bytes\"}[1m])) + sum(rate(tikv_engine_compaction_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"bytes_written\"}[1m]))",
     "legendFormat": "write-flow"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "sum(rate(tikv_engine_compaction_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"bytes_read\"}[1m]))",
     "legendFormat": "read-flow"
    }
   ]
  },
  {
   "title": "KVDB read SST too slow ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(tikv_engine_sst_read_micros{instance=~\"$instance\", db=\"kv\", type=\"sst_read_micros_percentile99\"})",
     "legendFormat": "duration-99%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "avg(tikv_engine_sst_read_micros{instance=~\"$instance\", db=\"kv\", type=\"sst_read_micros_max\"})",
     "legendFormat": "duration-max"
    }
   ]
  },
  {
   "title": "RaftDB compaction flow has jitter ? (read-flow may hit page-cache)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"flush_write_bytes\"}[1m])) + sum(rate(tikv_engine_compaction_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"bytes_written\"}[1m]))",
     "legendFormat": "write-flow"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "sum(rate(tikv_engine_compaction_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"bytes_read\"}[1m]))",
     "legendFormat": "read-flow"
    }
   ]
  },
  {
   "title": "KVDB read too much SSTs ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_engine_get_served{instance=~\"$instance\", db=\"kv\", type=~\"get_hit_l2_and_up|get_hit_l1\"}[1m]))",
     "legendFormat": "hit-count"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    }
   ]
  },
  {
   "title": "Total compaction flow has jitter ? (read-flow may hit page-cache)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"flush_write_bytes\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"flush_write_bytes\"}[1m])) + sum(rate(tikv_engine_compaction_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"bytes_written\"}[1m])) + sum(rate(tikv_engine_compaction_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"bytes_written\"}[1m]))",
     "legendFormat": "write-flow"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "sum(rate(tikv_engine_compaction_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"bytes_read\"}[1m])) + sum(rate(tikv_engine_compaction_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"bytes_read\"}[1m]))",
     "legendFormat": "read-flow"
    }
   ]
  },
  {
   "title": "KVDB seek too slow ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(tikv_engine_seek_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"seek_percentile99\"})",
     "legendFormat": "duration-99%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "avg(tikv_engine_seek_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"seek_max\"})",
     "legendFormat": "duration-max"
    }
   ]
  },
  {
   "title": "Total IO flow has jitter ? (read-flow may hit page-cache)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"flush_write_bytes\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"flush_write_bytes\"}[1m])) + sum(rate(tikv_engine_compaction_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"bytes_written\"}[1m])) + sum(rate(tikv_engine_compaction_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"bytes_written\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"wal_file_bytes\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"wal_file_bytes\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"bytes_written\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"bytes_written\"}[1m]))",
     "legendFormat": "write-flow"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "sum(rate(tikv_engine_compaction_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"bytes_read\"}[1m])) + sum(rate(tikv_engine_compaction_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"bytes_read\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"bytes_read\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"bytes_read\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"kv\", type=\"iter_bytes_read\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"iter_bytes_read\"}[1m]))",
     "legendFormat": "read-flow"
    }
   ]
  },
  {
   "title": "KVDB seek too much times ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_engine_locate{instance=~\"$instance\", db=\"kv\", type=\"number_db_next\"}[1m]))",
     "legendFormat": "count"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    }
   ]
  },
  {
   "title": "RaftDB frontend flow has jitter ? (read-flow may hit page-cache)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"wal_file_bytes\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"bytes_written\"}[1m]))",
     "legendFormat": "write-flow"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"bytes_read\"}[1m])) + sum(rate(tikv_engine_flow_bytes{instance=~\"$instance\", db=\"raft\", type=\"iter_bytes_read\"}[1m]))",
     "legendFormat": "read-flow"
    }
   ]
  },
  {
   "title": "Too many compaction pending bytes ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_engine_pending_compaction_bytes{instance=~\"$instance\", db=\"kv\"}[1m]))",
     "legendFormat": "pending-bytes-kv"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "sum(rate(tikv_engine_pending_compaction_bytes{instance=~\"$instance\", db=\"raft\"}[1m]))",
     "legendFormat": "pending-bytes-raft"
    }
   ]
  },
  {
   "title": "KVDB mutex lock too long ?",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_perf_context_time_duration_secs_bucket{instance=~\"$instance\", type=~\"db_mutex_lock_nanos|write_thread_wait\"}[1m])) by (le, type))",
     "legendFormat": "{{type}}-999"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_raftstore_apply_perf_context_time_duration_secs_bucket{instance=~\"$instance\", type=~\"db_mutex_lock_nanos|write_thread_wait\"}[1m])) by (le, type))",
     "legendFormat": "{{type}}-x"
    }
   ]
  }
 ]
}