{
 "title": "Test-Cluster-Performance-Write",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "kubernetes",
    "label": "Kubernetes",
    "query": "label_values(tikv_engine_block_cache_size_bytes, kubernetes)"
   },
   {
    "name": "tidb_cluster",
    "label": "tidb_cluster",
    "query": "label_values(tikv_engine_block_cache_size_bytes{kubernetes=\"$kubernetes\"}, tidb_cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "TiDB-Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration",
     "type": "graph",
     "description": "TiDB query durations by histogram buckets with different percents",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_server_handle_query_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_handle_query_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_server_handle_query_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le))",
       "legendFormat": "95"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_server_handle_query_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le))",
       "legendFormat": "80"
      }
     ]
    },
    {
     "title": "99% Get Token Duration",
     "type": "graph",
     "description": "Duration (us) for getting token, it should be small until concurrency limit is reached.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_server_get_token_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le))",
       "legendFormat": "99"
      }
     ]
    },
    {
     "title": "Connection Count",
     "type": "graph",
     "description": "TiDB current connection counts",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tidb_server_connections{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum(tidb_server_connections{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"})",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "description": "TiDB heap memory size in use ",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", job=~\"tidb.*\"}",
       "legendFormat": "{{instance}}-{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Parse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% Parse Duration",
     "type": "graph",
     "description": "The time cost of parsing SQL to AST",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_parse_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le, sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Compile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% Compile Duration",
     "type": "graph",
     "description": "The time cost of building the query plan",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_compile_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le, sql_type))",
       "legendFormat": "{{sql_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration",
     "type": "graph",
     "description": "Bucketed histogram of transaction execution durations, including retry",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_transaction_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le, sql_type))",
       "legendFormat": "99-{{sql_type}}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tidb_session_transaction_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le, sql_type))",
       "legendFormat": "95-{{sql_type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_session_transaction_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le, sql_type))",
       "legendFormat": "80-{{sql_type}}"
      }
     ]
    },
    {
     "title": "Transaction Statement Num",
     "type": "graph",
     "description": "TiDB statements numbers within one transaction. Internal means TiDB inner transaction",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_transaction_statement_num_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[30s])) by (le, sql_type))",
       "legendFormat": "99-{{sql_type}}"
      },
      {
       "expr": "histogram_quantile(0.80, sum(rate(tidb_session_transaction_statement_num_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[30s])) by (le, sql_type))",
       "legendFormat": "80-{{sql_type}}"
      }
     ]
    },
    {
     "title": "Transaction Retry Num",
     "type": "graph",
     "description": "TiDB transaction retry histogram bucket statistics",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(1.0, sum(rate(tidb_session_retry_num_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[30s])) by (le))",
       "legendFormat": "100"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_session_retry_num_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[30s])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(tidb_session_retry_num_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[30s])) by (le))",
       "legendFormat": "90"
      }
     ]
    }
   ]
  },
  {
   "title": "KV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "KV Cmd Duration 999",
     "type": "graph",
     "description": "kv command durations statistics by command type",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=~\"commit\"}[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Cmd Duration 99",
     "type": "graph",
     "description": "kv command durations statistics by command type",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_txn_cmd_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=~\"commit\"}[1m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Lock Resolve OPS",
     "type": "graph",
     "description": "lock resolve times",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_lock_resolver_actions_total{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "99% KV Backoff Duration",
     "type": "graph",
     "description": "kv command durations statistics by command type",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tidb_tikvclient_backoff_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[5m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "KV Backoff OPS",
     "type": "graph",
     "description": "kv storage backoff times",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tidb_tikvclient_backoff_seconds_count{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "PD Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "PD TSO Wait Duration",
     "type": "graph",
     "description": "The duration of a client calling GetTSAsync until received the TS result.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=\"tso\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=\"tso\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(pd_client_cmd_handle_cmds_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=\"tso\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    },
    {
     "title": "PD TSO RPC Duration",
     "type": "graph",
     "description": "The duration of a client sending TSO request until received the response.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=\"tso\"}[1m])) by (le))",
       "legendFormat": "999"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=\"tso\"}[1m])) by (le))",
       "legendFormat": "99"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(pd_client_request_handle_requests_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=\"tso\"}[1m])) by (le))",
       "legendFormat": "90"
      }
     ]
    }
   ]
  },
  {
   "title": "gRPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% gRPC message duration",
     "type": "graph",
     "description": "The execution time of gRPC message",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_grpc_msg_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=~\"kv_prewrite|kv_commit\"}[5m])) by (le, type))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "gRPC poll CPU",
     "type": "graph",
     "description": "The CPU utilization of gRPC",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(5, sum(rate(tikv_thread_cpu_seconds_total{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", name=~\"grpc.*\"}[1m])) by (instance, name))",
       "legendFormat": "{{ instance }} - {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scheduler latch wait duration",
     "type": "graph",
     "description": "the time which is caused by latch wait ",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_scheduler_latch_wait_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[5m])) by (le, type))",
       "legendFormat": "99% - {{ type }}"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_scheduler_latch_wait_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[5m])) by (le, type))",
       "legendFormat": "95% - {{ type }}"
      },
      {
       "expr": "rate(tikv_scheduler_latch_wait_duration_seconds_sum{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[5m]) / rate(tikv_scheduler_latch_wait_duration_seconds_count{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[5m])",
       "legendFormat": "avg - {{ type }}"
      }
     ]
    },
    {
     "title": "Scheduler worker CPU",
     "type": "graph",
     "description": "The CPU utilization of scheduler worker",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", name=~\"sched_.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "99% scheduler command duration",
     "type": "graph",
     "description": "The time consumed when executing commit command",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_scheduler_command_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le, type))",
       "legendFormat": "{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "raftstore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% propose wait duration by instance",
     "type": "graph",
     "description": "The wait time of each proposal",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_request_wait_time_duration_secs_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le, instance))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Raft store CPU",
     "type": "graph",
     "description": "The CPU utilization of raftstore thread",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", name=~\"raftstore_.*\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Storage async write duration",
     "type": "graph",
     "description": "The time consumed by processing asynchronous write requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_storage_engine_async_request_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=\"write\"}[5m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_storage_engine_async_request_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=\"write\"}[5m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": "sum(rate(tikv_storage_engine_async_request_duration_seconds_sum{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=\"write\"}[5m])) / sum(rate(tikv_storage_engine_async_request_duration_seconds_count{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", type=\"write\"}[5m]))",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB-Raft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% append log duration by instance",
     "type": "graph",
     "description": "The time consumed when Raft appends log on each TiKV instance",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_append_log_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le, instance))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Write duration",
     "type": "graph",
     "description": "The time consumed when executing write operation",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "max(tikv_engine_write_micro_seconds{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", db=\"raft\", type=\"write_max\"})",
       "legendFormat": "max"
      },
      {
       "expr": "max(tikv_engine_write_micro_seconds{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", db=\"raft\", type=\"write_percentile99\"})",
       "legendFormat": "99%"
      },
      {
       "expr": "max(tikv_engine_write_micro_seconds{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", db=\"raft\", type=\"write_percentile95\"})",
       "legendFormat": "95%"
      },
      {
       "expr": "max(tikv_engine_write_micro_seconds{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", db=\"raft\", type=\"write_average\"})",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB-KV",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "99% apply wait duration by instance",
     "type": "graph",
     "description": "The time consumed when apply log requests are wait for being handled",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_wait_time_duration_secs_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[5m])) by (le, instance))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Apply log duration",
     "type": "graph",
     "description": "The time consumed when Raft applies log",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_log_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le))",
       "legendFormat": " 99%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(tikv_raftstore_apply_log_duration_seconds_bucket{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_log_duration_seconds_sum{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) / sum(rate(tikv_raftstore_apply_log_duration_seconds_count{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[1m])) ",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Write duration",
     "type": "graph",
     "description": "The time consumed when executing write operation",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "max(tikv_engine_write_micro_seconds{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", db=\"kv\", type=\"write_max\"})",
       "legendFormat": "max"
      },
      {
       "expr": "max(tikv_engine_write_micro_seconds{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", db=\"kv\", type=\"write_percentile99\"})",
       "legendFormat": "99%"
      },
      {
       "expr": "max(tikv_engine_write_micro_seconds{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", db=\"kv\", type=\"write_percentile95\"})",
       "legendFormat": "95%"
      },
      {
       "expr": "max(tikv_engine_write_micro_seconds{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", db=\"kv\", type=\"write_average\"})",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Async apply CPU",
     "type": "graph",
     "description": "The CPU utilization of async apply",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_thread_cpu_seconds_total{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\", name=~\"apply_[0-9]+\"}[1m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Latency",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_disk_write_time_seconds_total{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[5m]) / irate(node_disk_writes_completed_total{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[5m])",
       "legendFormat": "Write: {{ instance }} - {{ device }}"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "graph",
     "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_disk_writes_completed_total{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[5m])",
       "legendFormat": "Write: {{ instance }} - {{ device }}"
      }
     ]
    },
    {
     "title": "Disk Bandwidth",
     "type": "graph",
     "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash storage life time.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_disk_written_bytes_total{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[5m])",
       "legendFormat": "Write: {{ instance }} - {{ device }}"
      }
     ]
    },
    {
     "title": "Disk Load",
     "type": "graph",
     "description": "Shows how much disk was loaded for reads or writes as average number of outstanding requests at different period of time.  High disk load is a good measure of actual storage utilization. Different storage types handle load differently - some will show latency increases on low loads others can handle higher load with no problems.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "irate(node_disk_write_time_seconds_total{kubernetes=\"$kubernetes\", tidb_cluster=\"$tidb_cluster\"}[5m])",
       "legendFormat": "Write: {{instance}} - {{ device }}"
      }
     ]
    }
   ]
  }
 ]
}