{
 "title": "Raftstore Async IO",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(tikv_engine_size_bytes, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Write RPC duration",
   "type": "graph",
   "description": "tikv_grpc_msg_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[30s])) by (le))",
     "legendFormat": "write-rpc-dur-99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[30s])) by (le))",
     "legendFormat": "write-rpc-dur-999%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_sum{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[30s])) / sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[30s]))",
     "legendFormat": "write-rpc-dur-avg"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Storage Async Write Duration",
   "type": "graph",
   "description": "tikv_storage_engine_async_request_duration_seconds_bucket",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_storage_engine_async_request_duration_seconds_bucket{instance=~\"$instance\", type=\"write\"}[30s])) by (le))",
     "legendFormat": "duration-999%"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[30s]))",
     "legendFormat": "write-rpc"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_storage_engine_async_request_duration_seconds_bucket{instance=~\"$instance\", type=\"write\"}[30s])) by (le))",
     "legendFormat": "duration-99%"
    },
    {
     "expr": "sum(rate(tikv_storage_engine_async_request_duration_seconds_sum{instance=~\"$instance\", type=\"write\"}[30s])) / sum(rate(tikv_storage_engine_async_request_duration_seconds_count{instance=~\"$instance\", type=\"write\"}[30s]))",
     "legendFormat": "duration-avg"
    }
   ]
  },
  {
   "title": "Imbalanced write ?",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}-write"
    },
    {
     "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[1m]))",
     "legendFormat": "write-rpc (total)"
    }
   ]
  },
  {
   "title": "Total Duration in Store Loop",
   "type": "graph",
   "description": "tikv_raftstore_store_duration_secs_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_duration_secs_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_duration_secs_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_duration_secs_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_duration_secs_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_duration_secs_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Total Duration in Apply Loop",
   "type": "graph",
   "description": "tikv_raftstore_apply_duration_secs_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_apply_duration_secs_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_duration_secs_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_duration_secs_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_duration_secs_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_apply_duration_secs_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Propose Wait Duration",
   "type": "graph",
   "description": "tikv_raftstore_request_wait_time_duration_secs_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_request_wait_time_duration_secs_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_request_wait_time_duration_secs_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_request_wait_time_duration_secs_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_request_wait_time_duration_secs_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_request_wait_time_duration_secs_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Apply Task To Write Queue Duration",
   "type": "graph",
   "description": "tikv_raftstore_apply_to_write_queue_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_apply_to_write_queue_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_to_write_queue_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_to_write_queue_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_to_write_queue_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_apply_to_write_queue_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Batch Wait Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_batch_wait_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_batch_wait_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_batch_wait_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_batch_wait_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_batch_wait_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_batch_wait_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Apply Task To Before Write State Duration",
   "type": "graph",
   "description": "tikv_raftstore_apply_to_write_state_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_apply_to_write_state_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_to_write_state_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_to_write_state_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_to_write_state_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_apply_to_write_state_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Task To Write Queue Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_to_write_queue_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_to_write_queue_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_to_write_queue_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_to_write_queue_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_to_write_queue_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_to_write_queue_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Apply Task To Before Write Duration",
   "type": "graph",
   "description": "tikv_raftstore_apply_to_write_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_apply_to_write_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_to_write_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_to_write_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_to_write_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_apply_to_write_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store  Task To Before Write Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_to_write_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_to_write_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_to_write_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_to_write_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_to_write_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_to_write_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Apply Task Write End Duration",
   "type": "graph",
   "description": "tikv_raftstore_apply_write_end_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_apply_write_end_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_write_end_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_write_end_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_write_end_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_apply_write_end_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Write KVDB End Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_write_kvdb_end_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_write_kvdb_end_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_write_kvdb_end_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_write_kvdb_end_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_write_kvdb_end_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_write_kvdb_end_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Apply Task To Callback Queue Duration",
   "type": "graph",
   "description": "tikv_raftstore_apply_in_callback_queue_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_apply_in_callback_queue_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_in_callback_queue_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_in_callback_queue_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_in_callback_queue_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_apply_in_callback_queue_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Task Write End Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_write_end_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_write_end_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_write_end_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_write_end_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_write_end_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_write_end_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Apply Task To Before Callback Duration",
   "type": "graph",
   "description": "tikv_raftstore_apply_before_callback_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_apply_before_callback_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_before_callback_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_before_callback_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_before_callback_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_apply_before_callback_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Task Know Persist Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_know_persist_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_know_persist_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_know_persist_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_know_persist_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_know_persist_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_know_persist_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Apply Proposal Count Per Write",
   "type": "graph",
   "description": "tikv_raftstore_apply_proposal_cnt_per_write_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_apply_proposal_cnt_per_write_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_proposal_cnt_per_write_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_proposal_cnt_per_write_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_proposal_cnt_per_write_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_apply_proposal_cnt_per_write_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Task Know Commit Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_know_commit_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_know_commit_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_know_commit_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_know_commit_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_know_commit_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_know_commit_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Task Schedule  Commit Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_schedule_commit_duration_seconds_bucket",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_schedule_commit_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_schedule_commit_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_schedule_commit_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_schedule_commit_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_schedule_commit_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  { "title": "Store Loop", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Store Write RaftDB Tick Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_write_loop_duration_seconds_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_write_loop_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_write_loop_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_write_loop_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_write_loop_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_write_loop_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Loop Tick Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_loop_duration_seconds_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_loop_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_loop_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_loop_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_loop_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_loop_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Write RaftDB Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_write_raftdb_duration_seconds_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_write_raftdb_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_write_raftdb_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_write_raftdb_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_write_raftdb_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_write_raftdb_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Loop Work Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_loop_work_duration_seconds_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_loop_work_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_loop_work_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_loop_work_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_loop_work_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_loop_work_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Async Writer Queue Size",
   "type": "graph",
   "description": "tikv_raftstore_store_write_queue_size_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_write_queue_size_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_write_queue_size_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_write_queue_size_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_write_queue_size_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_write_queue_size_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_raftstore_store_write_queue_size_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Store Write KVDB Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_write_kvdb_duration_seconds_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_write_kvdb_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_write_kvdb_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_write_kvdb_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_write_kvdb_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_write_kvdb_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Async Writer Adaptive Index",
   "type": "graph",
   "description": "tikv_raftstore_store_adaptive_idx_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 89 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_adaptive_idx_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_adaptive_idx_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_adaptive_idx_sum{instance=~\"$instance\"}[1m])) / sum(rate(tikv_raftstore_store_adaptive_idx_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_adaptive_idx_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "count"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_raftstore_store_adaptive_idx_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "RaftDB Write Efficiency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 89 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "avg(tikv_engine_bytes_per_write{instance=~\"$instance\", db=\"raft\",type=\"bytes_per_write_average\"}) / avg(tikv_engine_write_micro_seconds{instance=~\"$instance\", db=\"raft\",type=\"write_average\"}) * 1000000",
     "legendFormat": "write-efficiency-avg"
    },
    {
     "expr": "avg(tikv_engine_bytes_per_write{instance=~\"$instance\", db=\"raft\",type=\"bytes_per_write_average\"})",
     "legendFormat": "write-batch-size"
    }
   ]
  },
  {
   "title": "Store Async Writer Wait Lock Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_wait_lock_duration_seconds_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 94 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_wait_lock_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_wait_lock_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_wait_lock_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_wait_lock_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_wait_lock_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Async Writer IO Size",
   "type": "graph",
   "description": "tikv_raftstore_store_task_bytes_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 94 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_task_bytes_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_task_bytes_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_task_bytes_sum{instance=~\"$instance\"}[1m])) / sum(rate(tikv_raftstore_store_task_bytes_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "avg"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_task_bytes_count{instance=~\"$instance\"}[1m]))",
     "legendFormat": "count"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_raftstore_store_task_bytes_bucket{instance=~\"$instance\"}[1m])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Store Async Writer Hold Lock Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_hold_lock_duration_seconds_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_hold_lock_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_hold_lock_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_hold_lock_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_hold_lock_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_hold_lock_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Async Writer Expect IO Size",
   "type": "graph",
   "description": "tikv_raftstore_store_task_limit_bytes_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_task_limit_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_task_limit_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_task_limit_bytes_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_task_limit_bytes_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_task_limit_bytes_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(tikv_raftstore_store_task_limit_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Store Callback Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_write_callback_duration_seconds_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 104 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_write_callback_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_write_callback_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_write_callback_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_write_callback_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_write_callback_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Loop Work Duration (old)",
   "type": "graph",
   "description": "tikv_raftstore_raft_process_duration_secs_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 104 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_raft_process_duration_secs_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_raft_process_duration_secs_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_raft_process_duration_secs_bucket{instance=~\"$instance\"}[30s])) by (le, type))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_raft_process_duration_secs_bucket{instance=~\"$instance\"}[30s])) by (le, type))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_raft_process_duration_secs_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Store Task Wait For Write Duration",
   "type": "graph",
   "description": "tikv_raftstore_store_write_wait_duration_seconds_bucket",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tikv_raftstore_store_write_wait_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_store_write_wait_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_store_write_wait_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_store_write_wait_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
     "legendFormat": "999%"
    },
    {
     "expr": "sum(rate(tikv_raftstore_store_write_wait_duration_seconds_count{instance=~\"$instance\"}[30s]))",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Apply Loop",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apply Write KVDB Tick Duration",
     "type": "graph",
     "description": "tikv_raftstore_apply_write_loop_duration_seconds_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 86 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_loop_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_write_loop_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_write_loop_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_write_loop_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_loop_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Loop Tick Duration",
     "type": "graph",
     "description": "tikv_raftstore_apply_loop_duration_seconds_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 86 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_loop_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_loop_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_loop_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_loop_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_loop_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Write All Duration",
     "type": "graph",
     "description": "tikv_raftstore_apply_write_all_duration_seconds_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 91 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_all_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_write_all_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_write_all_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_write_all_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_all_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Loop Work Duration",
     "type": "graph",
     "description": "tikv_raftstore_apply_loop_work_duration_seconds_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 91 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_loop_work_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_loop_work_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_loop_work_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_loop_work_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_loop_work_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Write KVDB Duration",
     "type": "graph",
     "description": "tikv_raftstore_apply_write_kvdb_duration_seconds_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 96 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_kvdb_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_write_kvdb_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_write_kvdb_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_write_kvdb_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_kvdb_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "KVDB  Write Efficiency",
     "type": "graph",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 96 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "avg(tikv_engine_bytes_per_write{instance=~\"$instance\", db=\"kv\",type=\"bytes_per_write_average\"}) / avg(tikv_engine_write_micro_seconds{instance=~\"$instance\", db=\"kv\",type=\"write_average\"}) * 1000000",
       "legendFormat": "write-efficiency-avg"
      },
      {
       "expr": "avg(tikv_engine_bytes_per_write{instance=~\"$instance\", db=\"kv\",type=\"bytes_per_write_average\"})",
       "legendFormat": "write-batch-size"
      }
     ]
    },
    {
     "title": "Apply Async Writer Queue Size",
     "type": "graph",
     "description": "tikv_raftstore_apply_write_queue_size_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 101 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_write_queue_size_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_write_queue_size_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_queue_size_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_write_queue_size_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_queue_size_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      },
      {
       "expr": "histogram_quantile(1, sum(rate(tikv_raftstore_apply_write_queue_size_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Apply Async Writer IO Size",
     "type": "graph",
     "description": "tikv_raftstore_apply_task_bytes_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 101 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_task_bytes_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_task_bytes_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_task_bytes_sum{instance=~\"$instance\"}[1m])) / sum(rate(tikv_raftstore_apply_task_bytes_count{instance=~\"$instance\"}[1m]))",
       "legendFormat": "avg"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_task_bytes_count{instance=~\"$instance\"}[1m]))",
       "legendFormat": "count"
      },
      {
       "expr": "histogram_quantile(1, sum(rate(tikv_raftstore_apply_task_bytes_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Apply Async Writer Adaptive Index",
     "type": "graph",
     "description": "tikv_raftstore_apply_adaptive_idx_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 106 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_adaptive_idx_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_adaptive_idx_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_adaptive_idx_sum{instance=~\"$instance\"}[1m])) / sum(rate(tikv_raftstore_apply_adaptive_idx_count{instance=~\"$instance\"}[1m]))",
       "legendFormat": "avg"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_adaptive_idx_count{instance=~\"$instance\"}[1m]))",
       "legendFormat": "count"
      },
      {
       "expr": "histogram_quantile(1, sum(rate(tikv_raftstore_apply_adaptive_idx_bucket{instance=~\"$instance\"}[1m])) by (le))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Apply Async Writer Expect IO Size",
     "type": "graph",
     "description": "tikv_raftstore_apply_task_limit_bytes_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 106 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_task_limit_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_task_limit_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_task_limit_bytes_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_task_limit_bytes_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_task_limit_bytes_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      },
      {
       "expr": "histogram_quantile(1, sum(rate(tikv_raftstore_apply_task_limit_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "max"
      }
     ]
    },
    {
     "title": "Apply Async Writer Wait Lock Duration",
     "type": "graph",
     "description": "tikv_raftstore_apply_wait_lock_duration_seconds_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 111 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_wait_lock_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_wait_lock_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_wait_lock_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_wait_lock_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_wait_lock_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Callback Tick Duration",
     "type": "graph",
     "description": "tikv_raftstore_apply_write_callback_tick_duration_seconds_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 111 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_callback_tick_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_write_callback_tick_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_write_callback_tick_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_write_callback_tick_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_callback_tick_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Async Writer Hold Lock Duration",
     "type": "graph",
     "description": "tikv_raftstore_apply_hold_lock_duration_seconds_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 116 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_hold_lock_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_hold_lock_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_hold_lock_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_hold_lock_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_hold_lock_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Callback Duration",
     "type": "graph",
     "description": "tikv_raftstore_apply_write_callback_duration_seconds_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 116 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_callback_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_write_callback_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_write_callback_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_write_callback_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_callback_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Task Wait For Write Duration",
     "type": "graph",
     "description": "tikv_raftstore_apply_write_wait_duration_seconds_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 121 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_wait_duration_seconds_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_write_wait_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_write_wait_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_write_wait_duration_seconds_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_write_wait_duration_seconds_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  {
   "title": "Apply Loop Leader|Follower",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 115 },
   "collapsed": true,
   "panels": [
    {
     "title": "Apply Leader Write Keys",
     "type": "graph",
     "description": "tikv_raftstore_apply_leader_write_keys_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_leader_write_keys_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_leader_write_keys_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_leader_write_keys_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_leader_write_keys_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_leader_write_keys_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Leader Write  Bytes",
     "type": "graph",
     "description": "tikv_raftstore_apply_leader_write_bytes_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_leader_write_bytes_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_leader_write_bytes_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_leader_write_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_leader_write_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_leader_write_bytes_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Follower Write Keys",
     "type": "graph",
     "description": "tikv_raftstore_apply_follower_write_keys_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_follower_write_keys_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_follower_write_keys_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_follower_write_keys_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_follower_write_keys_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_follower_write_keys_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Follower Write Bytes",
     "type": "graph",
     "description": "tikv_raftstore_apply_follower_write_bytes_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_follower_write_bytes_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_follower_write_bytes_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_follower_write_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_follower_write_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_follower_write_bytes_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Leader Write Batch Keys",
     "type": "graph",
     "description": "tikv_raftstore_apply_leader_batch_write_keys_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_leader_batch_write_keys_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_leader_batch_write_keys_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_leader_batch_write_keys_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_leader_batch_write_keys_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_leader_batch_write_keys_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Leader Write Batch Bytes",
     "type": "graph",
     "description": "tikv_raftstore_apply_leader_batch_write_bytes_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_leader_batch_write_bytes_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_leader_batch_write_bytes_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_leader_batch_write_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_leader_batch_write_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_leader_batch_write_bytes_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Follower Write Batch Keys",
     "type": "graph",
     "description": "tikv_raftstore_apply_follower_batch_write_keys_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_follower_batch_write_keys_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_follower_batch_write_keys_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_follower_batch_write_keys_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_follower_batch_write_keys_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_follower_batch_write_keys_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    },
    {
     "title": "Apply Follower Write Batch Bytes",
     "type": "graph",
     "description": "tikv_raftstore_apply_follower_batch_write_bytes_bucket",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_raftstore_apply_follower_batch_write_bytes_sum{instance=~\"$instance\"}[30s])) / sum(rate(tikv_raftstore_apply_follower_batch_write_bytes_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "avg"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_raftstore_apply_follower_batch_write_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "99%"
      },
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_raftstore_apply_follower_batch_write_bytes_bucket{instance=~\"$instance\"}[30s])) by (le))",
       "legendFormat": "999%"
      },
      {
       "expr": "sum(rate(tikv_raftstore_apply_follower_batch_write_bytes_count{instance=~\"$instance\"}[30s]))",
       "legendFormat": "count"
      }
     ]
    }
   ]
  },
  {
   "title": "Report Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 116 },
   "collapsed": true,
   "panels": [
    {
     "title": "Write RPC count",
     "type": "graph",
     "description": "The count of different kinds of gRPC message",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_commit|kv_pessimistic_lock|kv_prewrite\"}[30s])) by (type)",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Write RPC duration",
     "type": "graph",
     "description": "The execution time of gRPC message",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[30s])) by (le))",
       "legendFormat": "write-rpc-dur-99%"
      }
     ]
    },
    {
     "title": "Write RPC duration",
     "type": "graph",
     "description": "The execution time of gRPC message",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(tikv_grpc_msg_duration_seconds_sum{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[30s])) / sum(rate(tikv_grpc_msg_duration_seconds_count{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[30s]))",
       "legendFormat": "write-rpc-dur-avg"
      }
     ]
    },
    {
     "title": "Write RPC duration",
     "type": "graph",
     "description": "The execution time of gRPC message",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.999, sum(rate(tikv_grpc_msg_duration_seconds_bucket{instance=~\"$instance\", type=~\"kv_prewrite|kv_commit|kv_pessimistic_lock\"}[30s])) by (le))",
       "legendFormat": "write-rpc-dur-999%"
      }
     ]
    }
   ]
  }
 ]
}