// Copyright 2016 TiKV Project Authors. Licensed under Apache-2.0.

mod test_bootstrap;
mod test_clear_stale_data;
mod test_compact_after_delete;
mod test_compact_lock_cf;
mod test_compact_log;
mod test_conf_change;
mod test_early_apply;
mod test_hibernate;
mod test_lease_read;
mod test_merge;
mod test_multi;
mod test_prevote;
mod test_region_change_observer;
mod test_region_heartbeat;
mod test_region_info_accessor;
mod test_replica_read;
mod test_service;
mod test_single;
mod test_snap;
mod test_split_region;
mod test_stale_peer;
mod test_stats;
mod test_status_command;
mod test_tombstone;
mod test_transfer_leader;
mod test_transport;
mod test_update_region_size;
