#!/usr/bin/env bash
# This script runs clippy with the most common configurations.
# Arguments given will be passed through to "cargo clippy"
# This runs in the Makefile environment via "make run"

set -euo pipefail

# Run from the Makefile environment
MAKEFILE_RUN=${MAKEFILE_RUN:-""}
if [[ -z $MAKEFILE_RUN ]] ; then
	COMMAND="$0 $*" exec make run
fi

ALLOWED_CLIPPY_LINTS=(-A clippy::module_inception  \
	-A clippy::should_implement_trait \
	-A clippy::new_without_default \
	-A clippy::too_many_arguments \
	-A clippy::blacklisted_name \
	-A clippy::needless_range_loop \
	-A clippy::new_ret_no_self \
	-A clippy::unnecessary_sort_by)

cargo clippy --workspace --all-targets --no-default-features \
	--exclude cdc --exclude backup --exclude tests --exclude cmd \
	--exclude fuzz-targets --exclude fuzzer-honggfuzz --exclude fuzzer-afl --exclude fuzzer-libfuzzer \
	--features "${TIKV_ENABLE_FEATURES}" -- "${ALLOWED_CLIPPY_LINTS[@]}"
for pkg in "components/cdc" "components/backup" "cmd" "tests"; do
	cd $pkg
	cargo clippy --all-targets --no-default-features \
		--features "${TIKV_ENABLE_FEATURES}" -- "${ALLOWED_CLIPPY_LINTS[@]}"
	cd - >/dev/null
done
for pkg in "fuzz"; do
	cd $pkg
	cargo clippy --all-targets -- "${ALLOWED_CLIPPY_LINTS[@]}"
	cd - >/dev/null
done
