#!/usr/bin/env bash

set -euo pipefail

# Use a standalone Rust toolchain to run cargo-deny independently from the code build environment.
RUST_VERSION="1.92.0"
rustup toolchain install $RUST_VERSION --profile minimal --no-self-update

# Keep cargo-deny on 0.18.9 to include the fix from https://github.com/tikv/tikv/pull/17987.
cargo +${RUST_VERSION} install --locked cargo-deny@0.18.9 2> /dev/null || echo "Install cargo-deny failed"
cargo +${RUST_VERSION} deny -V
cargo +${RUST_VERSION} deny fetch all
cargo +${RUST_VERSION} deny check --show-stats
