#!/usr/bin/env bash

set -euo pipefail

docker build -t tikv-dashboard-gen -f - . <<EOF
FROM pyfound/black:23.11.0

RUN pip install isort grafanalib==v0.7.0

CMD ["bash"]
EOF

docker run \
    --rm \
    -v ./metrics:/metrics \
    -e PYTHONDONTWRITEBYTECODE=1 \
    tikv-dashboard-gen \
    bash -c "\
        isort --profile black /metrics/grafana/*.py && \
        black /metrics/grafana/*.py && \
        generate-dashboard \
            -o /metrics/grafana/tikv_details.json \
            /metrics/grafana/tikv_details.dashboard.py
    "
